### PR TITLE
Add GPG exec options for #101

### PR DESCRIPTION
**Pull request by BorisKourt**
This appears to work properly. Do you need me to do anything else?

### CODE REVIEW

**Comment by BorisKourt** [comment]
Please check the current changes. 

I set `GPG_EXEC = None` to initialize it, not sure if this is a convention that works for you. 

I am new to the format of the README, but here is my edit in the branch: https://github.com/BorisKourt/sops/blob/gpg-exec-option/README.rst#specify-a-different-gpg-executable

**Comment by autrilla** [comment]
That change to the readme is fine. Keep in mind that you've made GPG_EXEC a global variable, and doing `GPG_EXEC = os.environ.get('SOPS_GPG_EXEC', 'gpg')` on `main` will just create a new variable in `main`'s scope instead of altering the global variable. You either want to use the global keyword, like this:
```
global UNENCRYPTED_SUFFIX
UNENCRYPTED_SUFFIX = args.unencrypted_suffix
```
, or just set `GPG_EXEC = os.environ.get('SOPS_GPG_EXEC', 'gpg')` on the global scope instead of inside main().

**Comment by BorisKourt** [comment]
Ah oops. I guess when I had the if earlier it simply passed the env check and then defaulted back to regular GPG. :/ 

I think I will go down the global route? It seems more appropriate to do the check with the other env checks.

**Comment by BorisKourt** [comment]
Updated

**Comment by autrilla** [comment]
Please fix the flake8 errors here https://travis-ci.org/mozilla/sops/jobs/156325475#L460 and then I can merge this.

**Comment by BorisKourt** [comment]
Alright, looks like `flake8` passed!

**Comment by autrilla** [comment]
Merged, thanks for the contribution!

**Comment by BorisKourt** [comment]
No problem, thanks for looking it over!

**Pull request merged**
