### PR TITLE
Add Azure CLI auth

### PR DESCRIPTION
**Pull request by autrilla**
Revives #425, more context there.

### CODE REVIEW

**Comment by autrilla** [comment]
The original commits were reviewed by me already. I don't think you've used Azure before @ajvb, but flagging you for review just so you're aware of what I've done. It might be good to wait for someone with Azure experience to review the docs I wrote.

**Comment by ptemmer** [comment]
Great to see this was merged. When can we expect this in a new release?

**Comment by ajvb** [comment]
@ptemmer Unless @autrilla wants to do one sooner, probably 2-3 weeks.

**Comment by ptemmer** [comment]
Hi there @ajvb. Any update on when to expect a new release, including this feature?
Thanks!!

**Comment by ajvb** [comment]
Hey @ptemmer, yes, we are coming close. Currently waiting on some testing of new features in `develop` by internal Mozilla teams and then we will be cutting a new release.

**Comment by ptemmer** [comment]
Great. Looking forward to it!

**Pull request merged**
