### PR TITLE
Upgrade to go 1.13

### PR DESCRIPTION
**Pull request by chenrui333**
Relates to https://github.com/Homebrew/homebrew-core/pull/44191

### CODE REVIEW

**Comment by chenrui333** [comment]
```
go: extracting github.com/Azure/go-autorest/autorest/to v0.2.0
go.mozilla.org/sops/config imports
	github.com/mozilla-services/yaml tested by
	github.com/mozilla-services/yaml.test imports
	go.mozilla.org/yaml.v2: cannot find module providing package go.mozilla.org/yaml.v2
Makefile:22: recipe for target 'vendor' failed
make: *** [vendor] Error 1
The command "if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then make; fi" exited with 2.
```

**Comment by novas0x2a** [comment]
one more change is necessary for full compat with 1.13:
```
$ go version
go version go1.13.3 linux/amd64
$ export GO111MODULE=on
$ go get go.mozilla.org/sops/cmd/sops@v3.4.0
go: finding go.mozilla.org/sops/cmd/sops v3.4.0
go: finding go.mozilla.org v3.4.0
go: finding go.mozilla.org/sops/cmd v3.4.0
go: finding go.mozilla.org/sops v3.4.0
go: finding go.mozilla.org/sops v3.4.0
go: finding go.mozilla.org/sops/cmd/sops v3.4.0
go get go.mozilla.org/sops/cmd/sops@v3.4.0: go.mozilla.org/sops@v3.4.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v3
```
The module line in the go.mod needs to be `go.mozilla.org/sops/v3` to match the go requirements around tagging and major versions.

**Comment by novas0x2a** [comment]
(and then every internal import needs to have /v3 appended to it, too. this is pretty painful)

**Comment by chenrui333** [comment]
As this has been addressed in the PR 566, closing it now.

**Pull request closed without merging**
