### PR TITLE
[PYTHON] Bump to 1.18

### PR DESCRIPTION
**Pull request by rouge8**
@autrilla @jvehent if you want to do another Python release :)

### CODE REVIEW

**Comment by rouge8** [comment]
I think I found an existing Python 3 bug with `--extract`... Closing for now and will try to take a look at that bug.

**Comment by rouge8** [comment]
Finally fixed the bug in https://github.com/mozilla/sops/pull/399

**Comment by rouge8** [comment]
Hmm, #399 didn't quite fix it for me... Will have a followup in a couple hours.

**Comment by rouge8** [comment]
D'oh, #399 is fine. My code that called `--extract` wasn't Python 3 compatible 😂

**Comment by rouge8** [comment]
@jvehent can you upload a new release to PyPI when you have a chance? 

Thanks again to both of you for quick reviews of the unmaintained Python version. :)

**Comment by jvehent** [comment]
1.18 is up on pypi https://pypi.org/project/sops/1.18/

**Pull request merged**
