### PR TITLE
readme: Fix typo

### PR DESCRIPTION
**Pull request by philipcristiano**

### CODE REVIEW

**Comment by philipcristiano** [comment]
Thanks for the quick response and reading the rest of that sentence!

**Comment by philipcristiano** [comment]
Is there anything else needed before this can be merged? I don't have any permissions on this repo to merge it.

**Comment by autrilla** [comment]
No, now we just need someone with write access to merge it.

cc @jvehent

**Comment by jvehent** [comment]
ohai @philipcristiano . Long time no see!

**Comment by philipcristiano** [comment]
Heya @jvehent! It has been, maybe seeing you a bit more in the future!

**Pull request merged**
