### PR TITLE
chore(gomod): Bumping AWS SDK version

### PR DESCRIPTION
**Pull request by sc250024**
Bumps the AWS SDK version to support more types of credential chaining.

## Description

It seems that the following issues:

- https://github.com/mozilla/sops/issues/619
- https://github.com/mozilla/sops/issues/679
- https://github.com/mozilla/sops/issues/686

Could potentially be helped with a simple bump of the AWS SDK version. Specifically my issue in the following comments...

- https://github.com/mozilla/sops/issues/619#issuecomment-668578276
- https://github.com/mozilla/sops/issues/679#issuecomment-668579715
- https://github.com/mozilla/sops/issues/686#issuecomment-668580178

...was resolved by simply bumping the AWS SDK version, compiling, and testing it out.

## Motivation and Context

Credential chaining did not work for me even though it should. My AWS credentials are obtained via [gimme-aws-creds](https://github.com/Nike-Inc/gimme-aws-creds) through Okta. This means that the `~/.aws/credentials` file uses temporary `aws_access_key_id` and `aws_secret_access_key` keys.

Using `AWS_PROFILE=development` uses another profile as a `source_profile` called `base`; the `base` profile is the one that has the credentials obtained through the [gimme-aws-creds](https://github.com/Nike-Inc/gimme-aws-creds) CLI tool.

Here are some example files:

<details>
<summary>~/.aws/credentials</summary>

```toml
[base]
aws_access_key_id = <redacted>
aws_secret_access_key = <redacted>
aws_session_token = <redacted>
aws_security_token = <redacted>
```

</details>

<details>
<summary>~/.aws/config</summary>

```toml
[profile base]
cli_pager =
region = us-east-1
output = json

[profile development]
cli_pager =
source_profile = base
role_arn = arn:aws:iam::111122223333:role/Administrator
region = us-east-1
output = json
```

</details>

The following error occurred when trying to create a new file:

```shell
$ AWS_PROFILE=development sops --verbose test.yaml

[AWSKMS]     INFO[0005] Encryption failed                             arn="arn:aws:kms:us-east-1:111122223333:key/11111c1d-b2c8-437d-ae4b-d00a123ccc45"
Error encrypting the data key with one or more master keys: [failed to encrypt new data key with master key "arn:aws:kms:us-east-1:111122223333:key/11111c1d-b2c8-437d-ae4b-d00a123ccc45": Failed to call KMS encryption service: NoCredentialProviders: no valid providers in chain. Deprecated.
    For verbose messaging see aws.Config.CredentialsChainVerboseErrors]
```

Which made no sense because the AWS SDK solved this a while ago. The version of the AWS SDK Sops was using before this PR [`v1.23.13`](https://github.com/aws/aws-sdk-go/releases/tag/v1.23.13) is now almost 1 year old.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by sc250024** [comment]
@autrilla It looks like there's some additional mock functions that are needed in `kms/mocks/KMSAPI.go`. Any hint on how to get those started?

**Comment by autrilla** [comment]
> @autrilla It looks like there's some additional mock functions that are needed in `kms/mocks/KMSAPI.go`. Any hint on how to get those started?

`make mock` should do the trick.

**Comment by sc250024** [comment]
> > @autrilla It looks like there's some additional mock functions that are needed in `kms/mocks/KMSAPI.go`. Any hint on how to get those started?
> 
> `make mock` should do the trick.

Ah cool, thank you! I just pushed the last commit after resolving Go dependencies. It's good to go from my side, let me know what you think.

**Comment by autrilla** [comment]
Oh, woops, you need to make this merge to `develop` instead of `master`.

**Comment by sc250024** [comment]
> Oh, woops, you need to make this merge to `develop` instead of `master`.

Done. Thank you for the approval 🙏

**Comment by sc250024** [comment]
@autrilla Is there anything else that's needed after the rebase?

**Comment by autrilla** [comment]
Nope, LGTM. Thanks!

**Comment by sc250024** [comment]
@autrilla Thank you sir!

**Pull request merged**
