### PR TITLE
[WIP] migrate to go mod from govend for dependency management

### PR DESCRIPTION
**Pull request by tariq1890**
Changing times call for new dependency management tools.

### CODE REVIEW

**Comment by autrilla** [comment]
I don't think we want to get rid of the vendored code in-repo, because there'll still be people that don't use go modules.

**Comment by tariq1890** [comment]
We aren't getting rid of the vendored code. I think the diff is misleading. You can check my branch to confirm.

**Comment by autrilla** [comment]
Before we merge, I'll have to remove all changes you've made to vendor/, since it's impossible to review the diff otherwise, and it'd be easy for attackers to sneak in malicious code. One this is all working, could you provide instructions on what you did to generate the changes to vendor/ so I can do that and commit the results myself?

**Comment by tariq1890** [comment]
Totally understand the concern. In that case, I'd suggest you commit all of the changes. It wouldn't make sense to merge this PR. Emailing you.

**Pull request closed without merging**
