### PR TITLE
Add Azure CLI authentication to sops

### PR DESCRIPTION
**Pull request by asw101**
This PR addresses Issue https://github.com/mozilla/sops/issues/418 and adds support for Azure CLI as well as [Managed Identity for Azure Resources](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview), formerly Managed Identity (MSI), to sops. 

It updates Azure/azure-sdk-for-go, Azure/go-autorest, including the addition of the OpenCensus dependencies.

This follows a chain of authentication methods, testing for a set of standard environment variables (AZURE_*), defined in our Azure SDK for Go, and an additional AZURE_AUTH_METHOD variable which enables us to force a particular authentication method.

Thank you @autrilla (who will review) and @Evesy who submitted the original issue.

Aaron

### CODE REVIEW

**Comment by asw101** [comment]
Thank you! I'll update the README -- my apologies for the delay. I also have some other README / sops on Azure usage tweaks I might be able to work in as well. Aaron

**Comment by carlpett** [comment]
This is amazing, thanks for implementing! :+1:

**Comment by Korijn** [comment]
Can I help finish up this PR?

**Comment by ethierhager** [comment]
I'm eager to try this feature out, so I tried building building from asw101/sops but I get this error: 

```
$ go build
# github.com/asw101/sops
./sops.go:76:6: cannot use logging.NewLogger("SOPS") (type *"go.mozilla.org/sops/vendor/github.com/sirupsen/logrus".Logger) as type *"github.com/asw101/sops/vendor/github.com/sirupsen/logrus".Logger in assignment
```

I'm not very familiar with golang, is there something I'm missing that would let me build it so I can test it out?

**Comment by ptemmer** [comment]
What's missing for this PR to be merged?

**Comment by autrilla** [comment]
> What's missing for this PR to be merged?

Documentation

**Comment by uipo78** [comment]
@asw101 throwing myself out there (just like @Korijn) if you're looking for help

**Comment by uipo78** [comment]
even if it's docs (it might take me a bit to figure out what needs to be written)

**Comment by autrilla** [comment]
@uipo78 feel free to open a new PR based on @asw101's work. As long as you keep the commit history there, I don't think there's any harm :). If you do so, remember to make the PR merge to the `develop` branch and not `master`.

I'd just want some docs in the readme around the `AZURE_AUTH_METHOD` variable since it's SOPS specific. Maybe a link to how the Azure SDK handles authentication, too.

Once that's done, we can merge this. I'll have to clean up the merge conflicts around vendoring, but that shouldn't be too hard.

**Comment by autrilla** [comment]
I've opened #496 adding some docs. It would be good if someone who actually uses Azure gave the docs a look for correctness, since I've never used it before.

**Comment by jvehent** [comment]
This PR is stale and conflicts with a lot of other files. Should we close it?

**Comment by autrilla** [comment]
Closing since this went stale, feel free to submit again with updated code.

**Pull request closed without merging**
