### PR TITLE
one line fix for install in readme

### PR DESCRIPTION
**Pull request by tcbtcb**
To do the `git checkout development` you need to be one extra level deep in the hierarchy.

### CODE REVIEW

**Comment by ajvb** [comment]
That's not how those version numbers work.

**Comment by felixfontein** [comment]
@ajvb that's how go works apparently :) If I repeat the steps, the current instructions fail because
```
~/go/src/go.mozilla.org/sops$ git branch
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
On the other hand,
```
~/go/src/go.mozilla.org/sops/v3$ git branch
* develop
  master
```

**Comment by felixfontein** [comment]
(This should be a PR against `develop` though...)

**Comment by ajvb** [comment]
Well then lol...

**Pull request closed without merging**
