### PR TITLE
Revert "Add standard newline/quoting behavior to dotenv store"

### PR DESCRIPTION
**Pull request by autrilla**
Reverts mozilla/sops#622

It seems based on #702 and #705 this change was not backwards compatible. I suggest we revert, make a new release and remove 3.6.0 from our Releases page.

### CODE REVIEW

**Comment by autrilla** [comment]
cc @scjudd who contributed the code that is accidentally backwards incompatible. I feel for now reverting is the best course of action, but we would be happy to take a modification of your original PR that doesn't have this issue.

**Comment by etiennetremel** [comment]
@ajvb @autrilla When do you expected to release v3.6.1?

**Comment by shadiramadan** [comment]
This v3.6.0 release caused me so many headaches.

**Comment by shadiramadan** [comment]
This was a *major* breaking change for us and a waste of time to root cause.  Either re-release 3.5 as 3.7 or if a fix is already made release it as 3.7.  Please don't leave a broken release just sitting there as you will cause headaches for another poor soul.

I also recommend following: https://semver.org/

Specifically- do not pretend a release never existed- release a new version.

**Comment by autrilla** [comment]
I can't make releases of sops anymore since I do not work for Mozilla.

I don't think semver says anything about removing versions from our download page. 3.6.0 exists and will continue to exist, but we don't want users downloading it.

**Comment by shadiramadan** [comment]
Here is a temporary workaround if someone needs it:
```
sops -d secrets.enc.env | sed -e "s/='/=/" -e "s/'$//" > secret.env
```

**Comment by shadiramadan** [comment]
> I don't think semver says anything about removing versions from our download page

No it doesn't and you should leave 3.6.0 up.  But it should at least be called out that it is broken on the release page and make a new release without the major breaking change.

Who does still work on this project?  sops is a great concept and very useful already.

**Comment by mltsy** [comment]
@ajvb is there someone else you can prod for a point release?

**Comment by mltsy** [comment]
@autrilla @ajvb @jvehent - any clues as to what's going on behind the scenes here?  Can anyone give a quick sense of what the normal release schedule looks like or if release have been suspended for some reason, etc.?  It's totally understandable that workflows can get a little off kilter based on human circumstances, especially right now - just some communication would be great!

Should we plan to live without a release of this for a significantly longer period of time (or fork the repo, or whatever makes sense)?  Or is work underway to get the release gears turning again?  Thanks for any insight you can provide!

**Comment by mltsy** [comment]
Oh, well 💩 - I guess [Mozilla laying off 250 people]( https://blog.mozilla.org/blog/2020/08/11/changing-world-changing-mozilla/) might have something to do with it, huh?  Yikes!

Is anybody on this project still employed?? 🙁

**Comment by autrilla** [comment]
I haven’t worked for Mozilla for over a year and I’ve still contributed to the project. That said, I haven’t been able to do releases since I left, for good reason. AFAIK there are contributors that are still employed by Mozilla — if not, I’m sure we can get someone to take over the project or move it to another organization.

**Comment by mltsy** [comment]
Thanks!  Well hopefully one of the other two folks can get word from someone who works at Mozilla.  It looks like @mozcloudsec has been doing the releases - I assume that's a service bot, so I guess it's anyone's guess who is actually capable of making a release 🤷‍♂️

Hey @mozcloudsec can you release 3.6.1 please? 🤖 😉

**Comment by ajvb** [comment]
@mltsy It's pretty hectic right now. I am currently the main Mozilla-employed maintainer right now and I am still here.

To be completely frank with you, sops issues that do not affect Mozilla are fairly low priority right now. There will be a release, but it may not be for a couple of weeks. I'm about to go on vacation and do not want to ship a new release right before leaving, as I am currently the only one familiar with sops who can ship a release.

**Comment by shadiramadan** [comment]
Thanks for weighing in @ajvb and providing some clarity.

> may not be for a couple of weeks

This little workaround is holding our org over so I'm _OK_  (not that I have a choice) waiting.
```
sops -d secrets.enc.env | sed -e "s/='/=/" -e "s/'$//" > secret.env
```

Have a great vacation!  I only ask that you set a reminder for after 😄

**Comment by shadiramadan** [comment]
Oh you know what that workaround only works for secrets with a single env entry.  I will be reverting to 3.5.0...

**Comment by ajvb** [comment]
@mltsy @shadiramadan @etiennetremel v3.6.1 is out with this fix - https://github.com/mozilla/sops/releases/tag/v3.6.1

**Comment by javierjulio** [comment]
@ajvb thanks! I submitted https://github.com/Homebrew/homebrew-core/pull/61126 to include the 3.6.1 release.

**Pull request merged**
