### PR TITLE
use golang 1.12 for building sops

### PR DESCRIPTION
**Pull request by tariq1890**
Golang 1.12 is the latest and should be sufficiently backwards-compatible.

### CODE REVIEW

**Comment by tariq1890** [comment]
The build failures don't seem to be related to the change.

**Comment by ajvb** [comment]
@tariq1890 No, the build failing is my fault. If @autrilla is +1 on this change I can prep it in a branch that will allow for the functional tests to run while I work on fixing them.

**Comment by tariq1890** [comment]
@autrilla Done

**Comment by tariq1890** [comment]
@ajvb Any plans to address the failing CI for master? This is a pretty widely-used project and I think it's imperative that it has stable CI pipelines.

**Comment by ajvb** [comment]
@tariq1890 We are going to try out using a `develop` branch as a mid point between PR's and master. Would you mind merging in the `develop` branch and pointing your PR at `develop` instead of `master`? Once that is done, we should be ready to merge this PR in.

**Comment by tariq1890** [comment]
Done

**Comment by ajvb** [comment]
Hey @tariq1890, you still need to merge `develop` into this branch.

**Comment by tariq1890** [comment]
@ajvb I have rebased on top the `develop` branch. PTAL.

**Pull request merged**
