### PR TITLE
 Match file path relative to config file's directory (2)

### PR DESCRIPTION
**Pull request by paulolieuthier**
`make test` shows no errors.

### CODE REVIEW

**Comment by autrilla** [comment]
Please make this merge onto develop, and rebase such that it's on top of the latest develop commit.

**Comment by paulolieuthier** [comment]
Ready.

**Review by autrilla — APPROVED** [review]

**Comment by paulolieuthier** [comment]
Looking forward to the next release!

**Comment by rayterrill** [comment]
@paulolieuthier @autrilla This change appears to be breaking things see #1029. Is there a plan to revert this, or mitigate?

**Comment by paulolieuthier** [comment]
Hey, @rayterrill thanks for pointing that out. I've commented on the issue, let's see where the maintainers will go with that.

**Pull request merged**
