### PR TITLE
Support referencing AWS KMS keys by aliases

### PR DESCRIPTION
**Pull request by darend**
## what

Allow KMS keys to be referenced by alias instead of the complete ARN

Example use:
```
creation_rules:
        - kms: "arn:aws:kms:us-west-2:1234567890:alias/my-sops-key,
                arn:aws:kms:us-east-1:1234567890:key/ba2dad9b-032f-42bd-aa69-6dd4012931f4"
```

## why

Addresses issue https://github.com/mozilla/sops/issues/381

## testing

Unit tests are passing, its not clear how to run the functional tests

### CODE REVIEW

**Comment by darend** [comment]
cc @snstanton

**Comment by darend** [comment]
> lgtm. I'm curious why you prefer using aliases vs the full ARN, though. They seem to be about as hard (read: impossible) to memorize as the ARN, since you'd have to memorize the account id, right?

We have multiple environments, each with its own set of keys. When we generate the key we use the environment name as the alias. This makes it very easy to configure sops since our tooling can derive the list of keys.

**Comment by autrilla** [comment]
I see, good to know!

**Comment by Wolfsrudel** [comment]
> > lgtm. I'm curious why you prefer using aliases vs the full ARN, though. They seem to be about as hard (read: impossible) to memorize as the ARN, since you'd have to memorize the account id, right?
> 
> We have multiple environments, each with its own set of keys. When we generate the key we use the environment name as the alias. This makes it very easy to configure sops since our tooling can derive the list of keys.

It's not just that: when the key rotates, the ID changes and you have to adjust the SOPS file. However, with an alias, this change is obsolete as the alias automatically points to the new (rotated) ID.

**Pull request merged**
