### PR TITLE
Added JSON example file

### PR DESCRIPTION
**Pull request by autrilla**

### CODE REVIEW

**Comment by jvehent** [comment]
Silly question: could we simply has this defined once as an anonymous struct and marshal it into whatever format needed?

**Comment by autrilla** [comment]
We could have a default tree, yes, but that would only work for json and yaml, we'd need to special-case binary files.

**Comment by jvehent** [comment]
Idea: add a "description" key to the struct that says `Welcome to SOPS! Remove this text and add your content to the file.`. When in BINARY mode, only print the value of `description`. When in other modes, just marshal the whole struct.

Benefit: if/when we add more formats, they'll just get the example data right away.

**Comment by autrilla** [comment]
I've made this change on #110 because I needed some of the changes there.

**Pull request closed without merging**
