### PR TITLE
Use rustup directly instead of actions-rs and run Go unit tests in Github Actions

### PR DESCRIPTION
**Pull request by autrilla**

### CODE REVIEW

**Review by ajvb — APPROVED** [review]
Awesome!

From looking at https://github.com/mozilla/sops/runs/1659479127?check_suite_focus=true - where are we running our go unit tests?

**Comment by autrilla** [comment]
Good point, looks like I forgot about that. Now they should run on all the OSs we build on.

**Comment by autrilla** [comment]
It's fixed now. Running tests on a cross-compiled binary doesn't work very well.

**Comment by ajvb** [comment]
Awesome!

**Pull request merged**
