### PR TITLE
Do not discard comments at beginning of YAML documents

### PR DESCRIPTION
**Pull request by felixfontein**
I couldn't find documentation mentioning that the top-of-document comments are discarded (that needs updating). @autrilla you mentioned that this behavior is documented in https://github.com/mozilla/sops/issues/695#issuecomment-659920093; can you point me to where?

Also, I couldn't run the functional tests since I don't have Rust set up right now, but I guess they'll run in CI :)

### CODE REVIEW

**Comment by autrilla** [comment]
I don't think it's in the readme, but it's in several issues, e.g. #300, #374, and probably others. I've found a few instances scattered in comments on several other issues.

This also fixes https://github.com/mozilla/sops/issues/384

**Review by autrilla — APPROVED** [review]

**Comment by autrilla** [comment]
Thanks again!

**Comment by felixfontein** [comment]
@autrilla thanks a lot for reviewing and merging! :)

BTW, is there a schedule/... for when a new release will happen?

**Comment by patricknelson** [comment]
Since this hasn't been released yet: Bump 😄 

Also, since I cannot test this, I want to confirm: Will this retain or discard comments throughout the document? I have a particular use case for `ytt` (YAML templating) such as an [encrypted values file](https://github.com/vmware-tanzu/carvel-ytt/blob/develop/docs/data-values-vs-overlays.md): 

```yaml
#@data/values
---
testing: 'foobar'
```

And since there are no values above that document divider `---`, it could still end up being discarded, but not sure.

**Comment by patricknelson** [comment]
p.s. If anyone lands here from a google search who _also_ happens to be using both `sops` and `ytt`, here's my current hack/workaround:

```bash
echo -e "#@data/values\n---\n$(sops -d encrypted-values.yml)" | ytt -f - -f template-file.yml
```

This prepends the necessary `ytt` comment and document separator and then uses the STDIN syntax `-f -`.

**Comment by felixfontein** [comment]
@patricknelson mozilla/sops#791 together with go-yaml/yaml#684 now preserves constructs such as
```.yaml
#@data/values
---
testing: 'foobar'
```

**Comment by patricknelson** [comment]
Oh ok cool @felixfontein! I commented here mainly since I _assumed_ that this merged PR would already perform that function. Is there a difference between your example and this new one below when it comes to this PR and the one you created?

```yaml
# comment
testing: 'foobar'
```

vs.

```yaml
# comment but as separate document
---
testing: 'foobar'
```

I only have to ask since I cannot test this since I'm unable to compile this and get it to work on my machine. So my gual is for this to hopefully get **released** soon 😄 (pretty please @autrilla 🙏).

**Comment by autrilla** [comment]
I'm not a project owner, so I can't create releases unfortunately.

**Comment by felixfontein** [comment]
@patricknelson this PR mainly bumps the version of the modified copy of yaml.v2 that is used by sops, which improves comment parsing. Since comment parsing is only part of the modified copy of yaml.v2, and not of the official yaml.v2, this is kind of a maintenance nightmare, since only sops developers are using this modified copy of yaml.v2 (at least that I'm aware of).

My new PR switches this modified copy of yaml.v2 by the official [yaml.v3](https://github.com/go-yaml/yaml/tree/v3) API, which does support comments. Unfortunately yaml.v3 is a work in progress itself, has bugs (w.r.t. comment processing) and not that actively developed (just compare https://github.com/go-yaml/yaml/commits/v3 with https://github.com/go-yaml/yaml/issues?q=is%3Aissue+is%3Aopen+v3). But still, since this is used by other projects, the chances of yaml.v3 being improved are higher than our modified copy of yaml.v2 being improved.

I've also created a PR for yaml.v3 which fixes some comment problems, including a bug which causes yaml.v3 to read your construct
```.yaml
#@data/values
---
testing: 'foobar'
```
as a single document
```.yaml
#@data/values
testing: 'foobar'
```
(which thus won't allow sops to treat it correctly). So when the yaml.v3 PR is merged (and a new version released), and the sops PR for using yaml.v3 is updated to use the latest yaml.v3 version, my new sops PR should be ready to go.

It's probably better to wait for the yaml.v3 version of sops, instead of releasing a new version with this PR included, to make sure that there's only one breaking change coming up (see https://github.com/mozilla/sops/pull/791#issuecomment-752548622).

@autrilla is @ajvb the only project owner at the moment?

**Comment by autrilla** [comment]
As far as I know, yes, but I think technically anyone in the @mozilla org has permission to do everything in this repo.

**Comment by patricknelson** [comment]
Just confirming that I'm using version 3.7.1 (released April 2021) and this feature still isn't yet available after a full year. I know it was merged into `develop`, but still... this isn't a breaking or backward incompatible, is it? Technically it does change output but I can't see how emitting a comment at the beginning of a YAML document would break things.

@ajvb just curious: what is the process/workflow for incorporating changes from `develop` into `master` so that they're ultimately released as an executable that we can use?

**Comment by felixfontein** [comment]
@patricknelson for me it's working with 3.7.1.

**Comment by patricknelson** [comment]
@felixfontein Got a _little_ egg on my face here; turns out I was actually using 3.**6**.1 and not 3.7.1. So the good news is that thankfully I can put comments at the top of YAML files which will help a little bit, however...

I just upgraded and found that my multi-document format (the format I still need it to support from `ytt`) is doing what you were describing in your last comment, specifically: The comment above the document separator `---` ends up coalescing incorrectly into a single document, which isn't valid (as `ytt` parses these comments and they still have semantic meaning).

> ```yaml
> #@data/values
> ---
> testing: 'foobar'
> ```
> 
> as a single document
> 
> ```yaml
> #@data/values
> testing: 'foobar'
> ```

So for now I'll still be using [my old polyfill script above](https://github.com/mozilla/sops/pull/757#issuecomment-748322761) in the meantime until a solution is found for that. I suppose _that_ is a separate issue unrelated to this ticket?

**Comment by patricknelson** [comment]
Seems like a separate issue (comments as their own document in a YAML stream), so I created #936 to track/discuss.

**Pull request merged**
