### PR TITLE
Encrypt comments

### PR DESCRIPTION
**Pull request by autrilla**
This is a first attempt at encrypting comments. It works, but the code in `sops.go` is very messy. A general cleanup of encrypting and decrypting would probably be good.

Requirements for merging:
- [x] Encrypts comments in new files
- [x] Decrypts encrypted comments in files
- [x] Does not try to decrypt unencrypted comments in files
- [x] Has tests (for all of the above, at least).

Fixes #230

### CODE REVIEW

**Comment by jvehent** [comment]
What's the backward compatibility story?

**Comment by autrilla** [comment]
This implementation doesn't add comments to the MAC, so it will be backwards compatible, but older SOPS versions will of course not decrypt comments.

(also apparently it's slightly broken, will fix soon)

**Comment by autrilla** [comment]
An example of the functionality:

```
sops git/encrypt-comments*  
❯ cat foo.yaml 
lorem: ipsum
# comment
dolor: sit
                                                                                                                                                                                                          
sops git/encrypt-comments*  
❯ sops -e foo.yaml > foo.enc.yaml
                                                                                                                                                                                                          
sops git/encrypt-comments*  
❯ cat foo.enc.yaml 
lorem: ENC[AES256_GCM,data:qfc7GJg=,iv:fMwcHtYhIIVwRvouiCKi8tacT2L8S0hqdi41/F3wL6o=,tag:v9dih5o0r++C+2283DfOGQ==,type:str]
#ENC[AES256_GCM,data:kY20ilfGuS0=,iv:IcU1G1i1YI51MjeI56Dkd7TAlK7x1vEKO7wLzfTqDO4=,tag:BEUo0fpoMg2Z+YdRW9VDzA==,type:comment]
dolor: ENC[AES256_GCM,data:zFNu,iv:AjMkquMoAy92KTBFtcm4EiRBIFCiWrAT43C3C5lYU8o=,tag:WwkgGcAtGqi2teLQFLIfCg==,type:str]
sops:
    kms: []
    lastmodified: '2017-08-15T20:59:55Z'
    mac: ENC[AES256_GCM,data:DYDPu1k3RPUs3a/5VSuUjz4IpzGh0ZSVJkK9F0lhNR7/K2hz+8qfmphjfCdi36ou/7LVkCvuFncbUJhma/zNtTd3k2NzrMNmlhMhnC7vbuJQmh4lUi/IWlgUocKm4SnA+V65WjvqwvItqXr9RQUC3m33g13i1LmFjifK9RpdgxU=,iv:IWOh40MG2aUAoKrpmNXxExlqjwPYTWYjHhDKsoIXmOA=,tag:ot6nhepGHM+pgnXkym673A==,type:str]
    pgp:
    -   created_at: '2017-08-15T20:59:55Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wYwDEEVDpnzXnMABBAAAcxeALjYMCkThpTxNDABY550dHdjMWe2FuyMyXxPpxdph
            KLEp0HYMEzYgcDCY+ghqd3hG4r4L5AzRlZ0ooeB+dk3KvS3dtWOuaVKhIQctQhxU
            0fM5AvAvwl3RGLVqSbifCviYHldvPAVa27QrSnKC+31xksD0cyhZBkLALejquNLg
            AeTsnlLy8JzjVzaBzgXaB9hF4UUN4KPgUuFNL+DI4mrM7fzgKOV73VgmCAWNSzwp
            yv7rvowcT4B3HUxqPx74FUr7vR1tfOC15KiCOgHPJEBvO95efH/MRAriNPVix+FZ
            dgA=
            =9ODF
            -----END PGP MESSAGE-----
        fp: 1022470DE3F0BC54BC6AB62DE05550BC07FB1A0A
    unencrypted_suffix: _unencrypted
    version: 2.0.9
                                                                                                                                                                                                          
sops git/encrypt-comments*  
❯ sops -d foo.enc.yaml 
lorem: ipsum
# comment
dolor: sit
```

**Comment by autrilla** [comment]
This now has tests and should be ready for review @jvehent

**Pull request merged**
