### PR TITLE
Revert "AWS Profile"

### PR DESCRIPTION
**Pull request by autrilla**
Reverts mozilla/sops#416

@marky-mark it looks like your PR broke SOPS assuming roles when not specifying a profile.

### CODE REVIEW

**Comment by jvehent** [comment]
How did this not get caught by the CI tests?

**Comment by autrilla** [comment]
> How did this not get caught by the CI tests?

The CI tests only use the real GPG implementation, everything else is mocked because we don't have AWS/GCP/Azure creds to run tests. So the AWS implementation mock assumes assuming roles will work.

**Comment by jvehent** [comment]
I think we should create test kms in aws and gcp and use them in CI.

**Comment by marky-mark** [comment]
Left a comment, think it’s the credentials type

**Pull request merged**
