### PR TITLE
Remove duplicate sentence from readme

### PR DESCRIPTION
**Pull request by michael-k**

### CODE REVIEW

**Comment by autrilla** [comment]
Can you make this merge against the `develop` branch?

**Comment by michael-k** [comment]
> Can you make this merge against the develop branch?

Of course, but it would be nice if this was mentioned in https://github.com/mozilla/sops/blob/master/CONTRIBUTING.md

**Comment by autrilla** [comment]
> 
> 
> > Can you make this merge against the develop branch?
> 
> Of course, but it would be nice if this was mentioned in https://github.com/mozilla/sops/blob/master/CONTRIBUTING.md

cc @ajvb is there any reason we don't?

**Comment by autrilla** [comment]
Thanks!

**Comment by michael-k** [comment]
I guess the change just hasn't made it to master yet.  It's mentioned in the `develop` branch: https://github.com/mozilla/sops/blob/develop/CONTRIBUTING.md

**Comment by ajvb** [comment]
@autrilla yeah, exactly what @michael-k said. Will create a PR to cut a new release for `3.3.1`.

**Pull request merged**
