### PR TITLE
Adding support for azure keyvault to key group config.

### PR DESCRIPTION
**Pull request by Devin-Holland**
Added support to the key group configuration to support AzureKV. It was added to the keyGroup struct but never used.

### CODE REVIEW

**Comment by ajvb** [comment]
@Devin-Holland This looks great! Thanks for doing this. Would you mind include azure keyvault config options within the tests (https://github.com/mozilla/sops/blob/master/config/config_test.go) as a part of this?

**Comment by Devin-Holland** [comment]
Won't get to look at that until Monday but I'll take a look then if no one gets to it before that.

**Comment by Devin-Holland** [comment]
`make test` doesn't seem to run on windows:

 ```
make test
GO15VENDOREXPERIMENT=1 GO111MODULE=on GOPROXY=https://proxy.golang.org go mod tidy
'GO15VENDOREXPERIMENT' is not recognized as an internal or external command,
operable program or batch file.
make: *** [Makefile:22: vendor] Error 1

```

**Comment by Devin-Holland** [comment]
@ajvb Testing added.

**Comment by autrilla** [comment]
> `make test` doesn't seem to run on windows:
> 
> ```
> make test
> GO15VENDOREXPERIMENT=1 GO111MODULE=on GOPROXY=https://proxy.golang.org go mod tidy
> 'GO15VENDOREXPERIMENT' is not recognized as an internal or external command,
> operable program or batch file.
> make: *** [Makefile:22: vendor] Error 1
> ```

You probably need to use an sh-like shell.

**Comment by autrilla** [comment]
Thanks for the patch!

**Comment by Devin-Holland** [comment]
Thanks! Is there a date set for the next release?

**Pull request merged**
